# Estados para ConversationHandlers
REPO_NAME, REPO_DESC, REPO_PRIVATE = range(3)
FORK_URL = 10
UPLOAD_REPO, UPLOAD_FILE = range(20, 22)
ZIP_REPO = 30
AI_MESSAGE = 40
SEARCH_QUERY = 50
URL_INPUT = 60
EDIT_REPO, EDIT_FILE, EDIT_CONTENT = range(70, 73)
